#!/bin/bash
# Outputs one newline for each key press
set -eu
trap 'kill $(jobs -p)' EXIT
_keyboard_ids="$(xinput list | grep -iE 'kb|keyboard' | grep -w 'slave' | grep -ow 'id=[0-9]*' | sed 's/id=//')"
_nobuf="stdbuf -i0 -o0 -e0"
for _keyboard_id in $_keyboard_ids; do
  $_nobuf xinput test "$_keyboard_id" </dev/null | $_nobuf grep -o 'key press' | $_nobuf sed 's/.*//' &
done
wait
