#!/bin/sh

# http://www.mspaintadventures.com/?s=6&p=001924

printf "%s" "You pull up to your COMPUTER. This is where you spend most of your time. You decorated your desktop with some rather handsome WALLPAPER which you made yourself. You are really proud of it.

Your desktop is also littered with various PROGRAMMING PROJECT FILES. You are so bad at programming sometimes you wonder why you even bother with it.

Your PESTERCHUM application is flashing. Someone is trying to get in touch with you.
"

script_basedir="$(dirname "$(readlink -f "$0")")"
exec "$script_basedir/fork" pidgin
