#!/bin/bash
set -eux
testdir="$(mktemp -d)"
scriptdir="$(dirname "$(readlink -f "$0")")"
cd "/var/empty" # Make sure the scripts don't need any given pwd.
echo "Testing scripts from $scriptdir in $testdir ..."
trap 'echo "test failed"' EXIT

echo "80characters plus newline"
test "$("$scriptdir/80characters" | wc -c)" = 81

echo "80characters sans newline"
# $() strips trailing newline if any.
test "$(printf '%s' "$("$scriptdir/80characters")" | wc -c)" = 80

trap - EXIT
echo "Success!"
